### ISSUE TITLE
OpenMode is not an enum

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-9p#11]
If the client tries to truncate a file, it gets this error from the server:

    S ((tag (0)) (payload (Err ((ename "Unknown mode number: 17") (errno ())))))

According to https://swtch.com/plan9port/man/man9/open.html:

> The mode field determines the type of I/O: 0 (called OREAD in <libc.h>), 1 (OWRITE), 2 (ORDWR), and 3 (OEXEC) mean read access, write access, read and write access, and execute access, to be checked against the permissions for the file. In addition, if mode has the OTRUNC (0x10) bit set, the file is to be truncated, which requires write permission (if the file is append-only, and permission is granted, the open succeeds but the file will not be truncated); if the mode has the ORCLOSE (0x40) bit set, the file is to be removed when the fid is clunked, which requires permission to remove the file from its directory. All other bits in mode should be zero.

**Comment by dsheets** [comment]
Fixed in https://github.com/dsheets/ocaml-9p/commit/0b8d60d3a1fd3207262b9f13093f2c0ea1368eb9
