### ISSUE TITLE
Double-checking that create works as expected

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-9p#23]
https://swtch.com/plan9port/man/man9/open.html says:

> Finally, the newly created file is opened according to mode, and fid will represent the newly opened file. Mode is not checked against the permissions in perm. The qid for the new file is returned with the create reply message.

The `fid` re-assignement was a bit surprising, so just creating an issue to be sure we don't forget (ideally we should have a unit-test)

**Comment by talex5** [comment]
Yes, looks like lofs9p doesn't update the FID on create (so it will still refer to the directory).

**Comment by dsheets** [comment]
Indeed. I will write a test for this and then fix it soonish.

**Comment by djs55** [comment]
Ah yes I just hit this myself.
