### ISSUE TITLE
Split unix and non-unix dependencies

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-9p#54]
We should split the unix and non-unix dependencies so that this is *actually* suitable for immediate use in Mirage apps. The new dep that is currently bothering me is `lambda-term` which is not necessary for the library but is for the new shell functionality which is a utility that only runs on Unix-like systems.

**Comment by djs55** [comment]
And @samoht had a similar issue (#66) with the unix-errno dependency -- I guess this is mainly needed for lofs?
