### ISSUE TITLE
Use CHANNEL rather than FLOW?

### ISSUE THREAD

**Issue by djs55** [mirage/ocaml-9p#83]
When parsing streams of 9P messages we want to be able to read the fixed-size header, extract the length and then read exactly the payload length. We currently implement our own buffered-packet-reader on top of `FLOW`:  https://github.com/mirage/ocaml-9p/blob/master/lib/protocol_9p_buffered9PReader.ml which has code which is suspiciously like the `CHANNEL` implementation in https://github.com/mirage/mirage-channel/blob/master/lib/channel.ml

Should we remove our ad-hoc buffering from there and layer a `CHANNEL` on top instead?

**Comment by samoht** [comment]
That sounds like a good idea :-)
